### PR TITLE
blog post

### PR DESCRIPTION
**Pull request by kcranston**
Comments on the blog post before we post to DC blog? @tracykteal @hlapp

### CODE REVIEW

**Comment by hlapp** [comment]
:+1:

**Comment by kcranston** [comment]
Hey @tracykteal - can you merge and post on the DC blog?

**Comment by debpaul** [comment]
Hi Karen,

Could you maybe add Florida State University after University of Florida? (iDigBio has 2 houses and I'm in the FSU house) thanks!
Best,
Deb
Sent from shoe (iPhone)

On Dec 14, 2015, at 8:02 PM, Karen Cranston <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey @tracyktealhttps://github.com/tracykteal - can you merge and post on the DC blog?

##

**Comment by tracykteal** [comment]
@kcranston Do you want me to put it up as a blog post on the DC blog, or do you want the DC blog to point to the post here?

**Comment by hlapp** [comment]
On further thought, putting this on the DC blog as is will seem to come a bit out of the blue. So I'd suggest that before this post goes up on DC, either we post an entry on the DC blog that announces the adoption of the Reproducible Science Curriculum by Data Carpentry (following on the heels of the rOpenSci partnership), or we preface this report with a blurb announcing this fact.

**Comment by tracykteal** [comment]
Good point. I think a blurb at the front of this would probably be best. I'll give it a quick try. Please edit the PR I'll put in.

**Pull request merged**
